name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build latest
        run: docker build . --tag therapywaffle/reacty:latest

      - name: Push latest
        run: docker push therapywaffle/reacty:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: docker

    steps:
      - name: Update and restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APP_SERVER_HOST }}
          username: ${{ secrets.APP_SERVER_USERNAME }}
          key: ${{ secrets.APP_SERVER_KEY }}
          port: ${{ secrets.APP_SERVER_PORT }}
          script: '~/restart-reacty.sh'
